name: 'gcc-toolchain'
description: 'Installs an x64 host gcc toolchain for cross compilation to arm. This action assumes the build is running on x64 Ubuntu 18.0.4.'
inputs:
  toolchain:
    description: 'Values: arm-rpi, aarch64, host'
    required: true
  version:
    description: 'Values by toolchain: arm-rpi [4.9.4, 6.5.0, 8.3.0] (Default: 6.5.0), aarch64 [7-N] (Default: 7), host [5-N] (Default: 8)'
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        TOOLCHAIN="${{ inputs.toolchain }}"
        INPUT_VERSION="${{ inputs.version }}"
  
        case "${{ inputs.toolchain }}" in
          arm-rpi)
            TOOLCHAIN_VERSION=${INPUT_VERSION:-6.5.0}
            wget https://github.com/lightsourceengine/ci/releases/download/v2.0.0/x64-gcc-${TOOLCHAIN_VERSION}.tar.xz
            tar -xJf x64-gcc-${TOOLCHAIN_VERSION}.tar.xz
            echo "${GITHUB_WORKSPACE}/x64-gcc-${TOOLCHAIN_VERSION}/arm-rpi-linux-gnueabihf/bin" >> $GITHUB_PATH
          ;;
          aarch64)
            sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
            sudo apt-get update
        
            if [[ -z "${INPUT_VERSION}" ]]; then
              sudo apt-get install -y g++-${TOOLCHAIN}      
            else
              sudo apt-get install -y g++-${INPUT_VERSION}-${TOOLCHAIN}
            fi
          ;;
          host)
            sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
            sudo apt-get update
            sudo apt-get install -y g++-${INPUT_VERSION:-8}
          ;;
        esac
      shell: bash
